---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hildy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:hildy-ai/hildy-kast.git
    targetRevision: master
    path: kast
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    retry:
      limit: 2
    syncOptions:
      - CreateNamespace=true