---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fwck
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kast-spells/spellbooks-library.git
    targetRevision: master
    path: kast
    helm:
      parameters:
        - name: "name"
          value: fwck
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    retry:
      limit: 2
    syncOptions:
      - CreateNamespace=true