FROM python:alpine3.18

# Install Helm, curl, and Python
RUN apk add --no-cache curl bash
WORKDIR /app
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
    && chmod +x get_helm.sh && VERIFY_CHECKSUM=false ./get_helm.sh && rm get_helm.sh


COPY ./src /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py"]
