# kast - Kubernetes arcane spelling technology
# Copyright (C) 2023 namenmalkv@gmail.com
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 
# NonCommercial (CC BY-SA-NC) license. See the LICENSE file for details.
{{- define "debug" -}}
{{- if (index . 0) -}}
{{ printf "%s:" (index . 2) }}
{{- toYaml (index . 1) | nindent 2 -}}
{{- end -}}
{{- end -}}


{{- define "configmap" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index . 0 }}
data:
  {{- toYaml (index . 1) | nindent 2 }}
{{- end -}}

{{- $spellbook :=  dict "appParams" $.Values.appParams  }}

#se puede agregar un if aca para q si no este definido el libro haga un "ls" y ver q libros hay y haga de multibook on one sweep

{{- $path := printf "library/%s/index.yaml" .Values.name }}
{{- if .Files.Glob $path }}
  {{- $default := .Files.Get $path | fromYaml }}
  {{- $_ := mergeOverwrite $default (dict "name" $.Values.name ) }}
  {{- $_ := mergeOverwrite $spellbook $default }}
{{- end }}

{{ include "debug" (list $.Values.debug $spellbook "spellbook" ) }}

##lexicon definition must be from a config map in some place
{{- $lexiconDefinition := dict }}
{{- $path := print "library/" $spellbook.name "/_lexicon/*.y*ml"}}
{{- $lexicon := list }}
{{- range $lexiconPath, $_ := .Files.Glob $path }}
  {{- $lexiconDefinitions := ($.Files.Get $lexiconPath | fromYaml).lexicon }}
  {{- range $lexiconDefinition := $lexiconDefinitions }}
    {{- $lexicon = append $lexicon $lexiconDefinition }}
  {{- end }}
{{- end }}
##lexicon merge 
{{- $_ := mergeOverwrite $spellbook (dict "lexicon" $lexicon) }}
{{ include "debug" (list $.Values.debug $spellbook "spellbook" ) }}
{{include "configmap" (list "lexicon" (dict "lexicon" $lexicon) )}}

{{ range $chapterName := $spellbook.chapters }}
  {{- $chapterIndex := dict }}
  {{- $path := print "library/" $spellbook.name "/" $chapterName "/index.yaml" }}
  {{- if $.Files.Glob $path }}
    {{- $chapterIndex = $.Files.Get $path | fromYaml }}
  {{- end }}
  {{- $path := print "library/" $spellbook.name "/" $chapterName "/*.y*ml"}}
  {{- range $spellPath, $_ := $.Files.Glob $path }}
  {{- if not (eq $spellPath (print "library/" $spellbook.name "/" $chapterName "/index.yaml")) }}
    {{- $sources := list }}
    {{- $appParams := deepCopy $spellbook.appParams }} 
    {{- $spellDefinition := ($.Files.Get $spellPath | fromYaml) }}
    {{- $_ := mergeOverwrite $appParams (default dict ($chapterIndex.appParams)) }}
    {{- $_ := mergeOverwrite $appParams (deepCopy (default dict ($spellDefinition.appParams ))) }}
    {{- $spell := (dict "name" $spellDefinition.name ) }}
    {{- if $spellDefinition.runes }}
      {{- range $rune := $spellDefinition.runes }}
        {{- $sources = append $sources $rune }}
        {{- $_ := mergeOverwrite $appParams (default dict $rune.appParams ) }}
      {{- end }}
    {{- end }}



---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $spellDefinition.name }}
  namespace: {{ default "argocd" $spellbook.argocdNamespace }}
  {{- with ($spellDefinition.app).customFinalizers }}
  finalizers:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with ($spellDefinition.app).annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  syncPolicy:
    {{- if $appParams.managedNamespaceMetadata }}
      {{- with $appParams.managedNamespaceMetadata }}
    managedNamespaceMetadata:
    {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if not $appParams.disableAutoSync }}
    {{- with $appParams.syncPolicy.automated }}
    automated:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- with $appParams.syncPolicy.syncOptions }}
    syncOptions:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $appParams.syncPolicy.retry }}
    retry:
    {{- toYaml . | nindent 6 }}
    {{- end }}  
  project: {{ default $spellbook.name $spellDefinition.useExistingProject }}
  sources:
  {{- $chart := "" }}
  {{- $path := "" }}
  {{- $repository := default $spellbook.defaultSpell.repository ($chapterIndex.defaultSpell).repository }}
  {{- $path := default $spellbook.defaultSpell.path ($chapterIndex.defaultSpell).path }}
  {{- $chart := default $spellbook.defaultSpell.chart ($chapterIndex.defaultSpell).chart}}
  {{- $revision := default $spellbook.defaultSpell.revision ($chapterIndex.defaultSpell).revision }}
  {{- if or $spellDefinition.chart $spellDefinition.path }}
  {{- $repository := $spellDefinition.repository }}
  {{- $path := $spellDefinition.path }}
  {{- $chart := $spellDefinition.chart }}
  {{- $revision := $spellDefinition.revision }}
  {{- end }}
    - repoURL: {{ $repository }}
      {{- if $chart }}
      chart: {{ $chart }}
      {{- else }}
      path: {{ $path }}
      {{- end }}
      targetRevision: {{ $revision }}
      helm:
      {{- if ($spellDefinition.app).skipCrds }}
        skipCrds: true
      {{- end }}
      {{- if not $spellDefinition.cleanDefinition }}
        parameters: #en este momento esto es un placeholder para ser usado pero todo esta sucediendo a nivel values
          - name: name
            value: {{ $spellDefinition.name }}
      {{- end }}
      {{- $definition := "" }}
      {{- if or $spellDefinition.chart $spellDefinition.path }}
      {{- $definition = $spellDefinition.definition }}
      {{- else }}
      {{- $definition = deepCopy $spellDefinition }}
      {{- $_ =  unset $definition "runes" }}
      {{- end }}
      {{- $cleanSpellbook := merge (dict "spellbook" (deepCopy $spellbook)) }}
      {{- $_ =  unset $cleanSpellbook.spellbook "appParams" }}
        values: |
          {{- if $spellDefinition }}
          {{- toYaml $definition | nindent 10 }}
          {{- end }}
          {{- if not $spellDefinition.cleanDefinition }}
          {{- toYaml $cleanSpellbook | nindent 10 }}
          chapter:
          {{- toYaml $chapterIndex | nindent 12 }}
          {{- end }}
    {{- if $spellDefinition.runes }}
    {{- range $rune := $spellDefinition.runes }}
    {{- $_ := mergeOverwrite $appParams (default dict $rune.appParams ) }}
      {{- if not $rune.name }}
        {{- $_ := merge $rune (dict "name" (printf "%s-rune" $spellDefinition.name))  }}
      {{- end }}
    - repoURL: {{ $rune.repository }}
      {{- if $rune.chart }}
      chart: {{ $rune.chart }}
        {{- else }}
      path: {{ $rune.path }}
        {{- end }}
      targetRevision: {{  $rune.revision }}
      helm:
        {{- if $rune.skipCrds }}
        skipCrds: true
        {{- end }}
        {{- if not $rune.addKastDefinitions }}
        parameters:
          - name: name
            value: {{ $rune.name }}
          - name: spell.name
            value: {{ $spellDefinition.name }}
        {{- end}}
        values: |
          {{- if $rune.definition }}
          {{- toYaml $rune.definition | nindent 10 }}
          {{- end }}
          {{- if not $spellDefinition.addKastDefinitions }}
          {{- toYaml $spellbook | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ if $spellDefinition.namespace }}{{ $spellDefinition.namespace }}{{ else }}{{ default $spellDefinition.name $spellDefinition.namespace }}{{ end }}
  {{- if ($appParams).ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml $appParams.ignoreDifferences | nindent 4 }}
  {{- end }}




   {{ include "debug" (list $.Values.debug $sources $spellPath ) | nindent 0 }}
  {{- end }}
  {{- end }}
{{- end }}
