{{ if not .Values.projectDisabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default (default $.Values.projectName  $.Values.name ) $.Release.Name  }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}