{{ if not .Values.projectDisabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default $.Release.Name (default $.Values.name $.Values.projectName) }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}